# Generated by Django 4.1.6 on 2023-02-09 10:15

from django.db import migrations, models

import helpers.image_paths


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, upload_to=helpers.image_paths.upload_profile_image),
        ),
    ]
