# Generated by Django 4.1.6 on 2023-02-22 15:07

from django.db import migrations, models

import helpers.image_paths


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_profile_date_of_birth_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                default=helpers.image_paths.default_profile_image,
                upload_to=helpers.image_paths.upload_profile_image,
            ),
        ),
    ]
