# Generated by Django 4.1.6 on 2023-02-22 11:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transport", "0006_auto_20230217_2347"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BusStop",
        ),
    ]
