# Generated by Django 4.1.6 on 2023-02-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transport", "0007_delete_busstop"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="rate",
            field=models.IntegerField(
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")]
            ),
        ),
    ]
