# Generated by Django 4.1.6 on 2023-02-25 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transport", "0008_alter_review_rate"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="transportation",
            name="transport_t_number_f05808_idx",
        ),
        migrations.AddIndex(
            model_name="transportation",
            index=models.Index(fields=["-route"], name="transport_t_route_965d4b_idx"),
        ),
    ]
