# Generated by Django 4.1.6 on 2023-03-11 21:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "transport",
            "0009_remove_transportation_transport_t_number_f05808_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="transportation",
            name="type",
            field=models.CharField(
                choices=[
                    ("bus", "Bus"),
                    ("microbus", "Microbus"),
                    ("trolleybus", "Trolleybus"),
                    ("metro", "Metro"),
                ],
                max_length=120,
            ),
        ),
    ]
