# Generated by Django 4.1.6 on 2023-03-12 14:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transport", "0010_alter_transportation_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transportation",
            name="stop",
        ),
    ]
