# Generated by Django 3.2.5 on 2023-02-17 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('letter', models.CharField(default='', max_length=2)),
                ('region', models.CharField(choices=[('aragatsotn', 'Aragatsotn'), ('ararat', 'Ararat'), ('armavir', 'Armavir'), ('gegharquniq', 'Gegharquniq'), ('lory', 'Lory'), ('kotayq', 'Kotayq'), ('shirak', 'Shirak'), ('syunik', 'Syunik'), ('vayots dzor', 'Vayots Dzor'), ('tavush', 'Tavush'), ('yerevan', 'Yerevan')], default='yerevan', max_length=20)),
            ],
        ),
    ]
